apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: laptop.int
  - name: https
    protocol: HTTPS
    port: 443
    hostname: laptop.int
    tls:
      mode: Terminate
      certificateRefs:
      - name: tls-secret

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: apple-banana-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - laptop.int
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /apple
    backendRefs:
    - name: apple-service
      port: 5678
  - matches:
    - path:
        type: PathPrefix
        value: /banana
    backendRefs:
    - name: banana-service
      port: 5678
